#!/bin/sh
run() {
	../build/txt2latex $1 > "$1.tex"
    ../build/txt2latex -a "User Command" -t "txt2latex(1)" \
        -I "OPTION" -I "ARGS" -I "FILE" -B "txt2latex" \
        --man $1 > "$1_doc.tex"
    cp -v "${1%.txt}.tex" "$1.tex"
	diff -u "${1%.txt}.tex" "$1.tex"
}

#trap "rm -f out" EXIT
nerr=0

for t in *.txt; do
	if run "$t"; then
		echo "$t: PASS"
	else
		echo "$t: FAIL"
		nerr=$((nerr + 1))
	fi
done

if [ $nerr != 0 ]; then
	echo "$nerr tests FAIL"
	exit 1
fi
