#!/bin/sh

run() {
	../build/txt2latex -a "M. Skocic" -d "2026/04" -t "Title" -I "itemize" -I "enumerate" -I "description" -B "description" $1 > out
	diff -u "${1%.txt}.tex" out
}

trap "rm -f out" EXIT
nerr=0

for t in *.txt; do
	if run "$t"; then
		echo "$t: PASS"
	else
		echo "$t: FAIL"
		nerr=$((nerr + 1))
	fi
done

if [ $nerr != 0 ]; then
	echo "$nerr tests FAIL"
	exit 1
fi
