#!/bin/sh

run() {
	../build/txt2latex $1 > out.tex
	diff -u "${1%.txt}.tex" out.tex
	../build/txt2latex -a "Author" -d "YYYY/MM/DD" -t "Title" -I "itemize" -I "enumerate" -I "description" -B "description" $1 > dout.tex
}

#trap "rm -f out" EXIT
nerr=0

for t in *.txt; do
	if run "$t"; then
		echo "$t: PASS"
	else
		echo "$t: FAIL"
		nerr=$((nerr + 1))
	fi
done

if [ $nerr != 0 ]; then
	echo "$nerr tests FAIL"
	exit 1
fi
