#!/usr/bin/env bash

export APP_VERSION=$(tr -d '\r' < VERSION | tr -d '\n')
export APP_NAME="txt2latex"
export APP_SRC_DIR="src"
export APP_BUILD_DIR="build"
export APP_MAN_SEC="1"
export APP_MAN_DIR="man/man$APP_MAN_SEC"
export APP_MAN_NAME=$APP_NAME.$APP_MAN_SEC


envs=$(printenv | grep ^APP)
IFS=$'\n'
echo "# Autogenerated" > make.in
for i in $envs; do
    echo $i
    echo "export $i" >> make.in
done

mkdir -p $APP_BUILD_DIR

IFS=$'\n'
sed -E -i "s/=\"(0|[1-9]\d*)\.(0|[1-9]\d*)\.?(0|[1-9]\d*)?/=\"$APP_VERSION/g" "$APP_SRC_DIR/$APP_NAME.sh"

