#!/usr/bin/env bash

# DEFINE
PROGNAME="txt2latex"
PROGVERSION="0.1.6"
SHORTDESCRIPTION="Converts text to LaTeX."
HOMEPAGE="https://github.com/MilanSkocic/txt2latex"
LICENSE="MIT"
AUTHOR="M. Skocic"
MANSECTION="1"
RED="\e[31m"
BLACK="\e[0m"
GREEN="\e[32m"


help () {
cat << EOT
NAME
  $PROGNAME - convert flat ASCII text to LaTeX.

SYNOPSIS
  $PROGNAME [OPTION...] FILE 

DESCRIPTION
  $PROGNAME converts the input text into LaTeX. The conversion procedure
  is strongly inspired by txt2man.

  $PROGNAME is also able to recognize and format sections, paragraphs,
  lists (standard, numbered, description, nested), literal display blocks.

  If input file FILE is omitted, standard input is used. 
  Result is displayed on standard output. 

  Here is how text patterns are recognized and processed:
  Sections    These headers are defined by a line in upper case, starting
              column 1. 
              Optionnally, the Section name can be preceded by a blank line. 
              This is useful for a better visualization of the source 
              text to be used to generate the LaTeX source code.
  Paragraphs  They must be separated by a blank line, and left aligned.
              Alternatively two blank spaces can be used to produce the
              same result. This option will provide a better visualization
              of the source text to be used to generate the LaTeX source code.
  Description list  
              The item definition is separated from the item description
              by at least 2 blank spaces, even before a new line, if
              definition is too long.
  Bullet list  
              Bullet list items are defined by the first word being "-"
              or "*" or "o".
  Enumerated list  
              The first word must be a number followed by a dot or a round bracket.
  Literal display blocks  
              This paragraph type is used to display unmodified text,
              for example source code. It must be separated by a blank
              line and be indented by a TAB. It is primarily used to format
              unmodified source code. It will be printed using fixed font
              using verbatim environment.
  Mathematics  
              Inline mathematics must be enclosed with round brackets 
              and equations must be enclosed with squared brackets.
              Brackets must be escaped with a blackslash.

OPTIONS
  -v, --version   Display version.
  -h, --help      Display help.
  -d date         Set date. Defaults to current date.
  -t mytitle      Set the title. If the title is set, txt2latex will 
                  automatically add the preambule and tags for the document
  -a author       Set the author.
  -s shift        Shift heading level by 0 (section), 1 (subsection), or 2 (subsection).
                  Defaults to 0.
  -I txt          Italicize txt in output. Can be specified more than once.
  -B txt          Emphasize (bold) txt in output. Can be specified more than once.
  -P package      Add packages or LateX commands in the preambule.
                  LateX commands must be doubled escaoed e.g. \\\\usepackage{ccfonts}.
  -X              Compile output with pdflatex.

EXAMPLES
  Simple conversion

        $ $PROGNAME FILE > FILE.tex
  
  Conversion with document title

        $ $PROGNAME -t "title" -a "author" -I "word" FILE > FILE.tex

  Conversion with custom packages and direct rendering with pdflatex

        $ $PROGNAME -t "title" -a "author" -I "word" -P "\\\\usepackage{ccfonts}" -X FILE

SEE ALSO
  txt2man(1)
EOT
}


version () {
echo "PROGRAM:      $PROGNAME                          "
echo "DESCRIPTION:  $SHORTDESCRIPTION                  "
echo "VERSION:      $PROGVERSION                       "
echo "AUTHOR:       $AUTHOR                            "
echo "LICENSE:      $LICENSE                           "
}

title=
author=
date=${date:-$(date +'%d %B %Y')}
itxt=
btxt=
post=cat

args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --help)
      args+=("-h")
      shift
      ;;
    --version)
      args+=("-v")
      shift
      ;;
    --) # end of options
      shift
      break
      ;;
    -*)
      args+=("$1")
      shift
      ;;
    *)
      break
      ;;
  esac
done

# Restore positional parameters
set -- "${args[@]}" "$@"

while getopts :vhd:t:a:I:B:P:X opt
do
	case $opt in
	(d) date=$OPTARG;;
	(t) title=$OPTARG;;
	(a) author=$OPTARG;;
	(I) itxt="$OPTARG§$itxt";;
	(B) btxt="$OPTARG§$btxt";;
	(P) ptxt="$OPTARG§$ptxt";;
    (X) post="pdflatex";;
	(h) help; exit;;
	(v) version; exit;;
    :) echo "Option -$OPTARG requires an argument"; exit 1;;
#    \?) echo "Invalid option: -$OPTARG"; exit 1;;
    *) exit;;
	esac
done
shift $(($OPTIND - 1))


if [[ ${#@} == 0 ]];then
    if [[ -t 0 ]]; then
        echo "No input from stdin or from file."
        exit 1;
    fi
fi

head="%Text automatically generated by txt2latex"

expand $@ | 
gawk --re-interval -v head="$head" -v title="$title" -v author="$author" -v date="$date" \
 -v itxt="$itxt" \
 -v btxt="$btxt" \
 -v ptxt="$ptxt" '
BEGIN {
	print head
	avar[1] = btxt; avar[2] = itxt
	for (k in avar) {
		#M mark = (k == 1) ? "\\fB" : "\\fI"
		mark = (k == 1) ? "\\textbf{" : "\\textit{"
		split(avar[k], tt, "§")
		for (i in tt)
			if (tt[i] != "")
				#M subwords["\\<" tt[i] "\\>"] = mark tt[i] "\\fP"
				subwords["\\<" tt[i] "\\>"] = mark tt[i] "}"
		for (i in tt)
			delete tt[i]
	}
	for (k in avar)
		delete avar[k]

    if (title != "") {
        start_article(title, author, date); 
        start_document()
    }
}
END{ 
    #M 
    in_list=end_list(in_list,"itemize")
    in_desc=end_list(in_desc,"description")
    in_enum=end_list(in_enum,"enumerate")
    in_bd=end_list(in_bd, "verbatim")
    if (title != "") {end_document()} 
}
{
	#M Do nothing for equation environment $$...$$
    if (match($0,/[[:space:]].*\$\$(.*)\$\$/)>0) {
        print $0
        next
    }
    #M Format lines with inline math
    if ((in_bd+0) == 0) {
        $0=fmtmath($0)
    }

    # to avoid some side effects in regexp
	gsub(/\.\.\./, "\\ldots")
	# remove spaces in empty lines
	sub(/^ +$/,"")
}
/^[[:upper:][:digit:]]+[[:upper:][:space:][:digit:][:punct:]]+$/ {
	# Section header
	if ((in_bd + 0) == 1) {
		in_bd = 0
		#M print ".fam T\n.fi"
        print "\\end{verbatim}"
	}
	if (section == "SYNOPSIS") {
		#M print ".fam T\n.fi"
		type["SYNOPSIS"] = ""
	}
	if ($0 ~/^[^[:space:]]/)
		#M print ".SH " $0
		print "\\section{" $0 "}"
	else
		#M print ".SS" $0
		print "\\subsection{" $0 "}"
	sub(/^ +/, "")
	section = $0
	if (section == "SYNOPSIS") {
		#M print ".nf\n.fam C"
		#M in_bd = 1
	}
	ls = 0		# line start index
	pls = 0		# previous line start index
	pnzls = 0	# previous non zero line start index
	ni = 0		# indent level
	ind[0] = 0	# indent offset table
	prevblankline = 0
	next
}
{
	# Compute line start index, handle start of example display block
	pls = ls
	if (ls != 0)
		pnzls = ls
	match($0, /[^ ]/)
	ls = RSTART
	if (in_bd == 0 && pls == 0 && pnzls > 0 && ls > pnzls && $1 !~ /^[\-\*o]$|^[0-9]+\.$/) {
		# example display block
		if (prevblankline == 1) {
			#M print ".PP"
			prevblankline = 0
		}
		#M print ".nf\n.fam C"
        in_bd = start_list(in_bd, "verbatim")
		eoff = ls
	}
	if (ls > 0 && ind[0] == 0)
		ind[0] = ls
}
(in_bd + 0) == 1 {
	# In block display
	if (section == "SYNOPSIS")
		;
	else if (ls != 0 && ls < eoff) {
		# End of literal display block
		#in_bd = 0
		#M print ".fam T\n.fi"
        in_bd = end_list(in_bd, "verbatim")
	} else { print; next }
}
section == "NAME" {
	#M $1 = "\\fB" $1
	$1 = "\\textbf{" $1 "}"
	#M sub(/ \- /, " \\fP- ")
}
section == "SYNOPSIS" {
	# Identify arguments of fcts and cmds
	if (type["SYNOPSIS"] == "") {
		if ($0 ~ /\(/)
			type["SYNOPSIS"] = "fct"
		else if ($1 == "struct" || $2 == "struct")
			type["SYNOPSIS"] = "struct"
		else if ($1 && $1 !~ /^#|typedef|struct|union|enum/)
			type["SYNOPSIS"] = "cmd"
	}
	if (type["SYNOPSIS"] == "cmd") {
		# Line is a command line
		if ($1 !~ /^\[/) {
			b = $1
			sub(/^\*/, "", b)
			#M subwords["\\<" b "\\>"] = "\\fB" b "\\fP"
			subwords["\\<" b "\\>"] = "\\textbf{" b "}"
		}
		for (i = 2; i <= NF; i++) {
			a = $i
			gsub(/[\[\]\|]/, "", a)
			if (a ~ /^[^\-]/)
				#M subwords["\\<" a "\\>"] = "\\fI" a "\\fP"
				subwords["\\<" a "\\>"] = "\\textit{" a "}"
		}
	} else if (type["SYNOPSIS"] == "fct") {
		# Line is a C function definition
		if ($1 == "typedef") {
			if ($0 !~ /\(\*/)
				#M subwords["\\<" $2 "\\>"] = "\\fI" $2 "\\fP"
				subwords["\\<" $2 "\\>"] = "\\textit{" $2 "}"
		} else if ($1 == "#define")
			#M subwords["\\<" $2 "\\>"] = "\\fI" $2 "\\fP"
			subwords["\\<" $2 "\\>"] = "\\textit{" $2 "\\}"
		for (i = 1; i <= NF; i++) {
			if ($i ~ /[,\)];*$/) {
				a = $i
				sub(/.*\(/, "", a)
				gsub(/\W/, "", a)
				#M subwords["\\<" a "\\>"] = "\\fI" a "\\fP"
				subwords["\\<" a "\\>"] = "\\textit{" a "}"
			}
		}
	}
}
{
	# protect dots inside words
	while ($0  ~ /\w\.\w/)
		sub(/\./, "_dOt_")
	# identify func calls and cross refs
	for (i = 1; i <= NF; i++) {
		b = $i
		sub(/^\*/, "", b)
		if ((a = index(b, ")(")) > 3) {
			w = substr(b, 3, a - 3)
			#M subwords["\\<" w "\\>"] = "\\fI" w "\\fP"
			subwords["\\<" w "\\>"] = "\\textit{" w "}"
		}
		if ((a = index(b, "(")) > 1) {
			w = substr(b, 1, a - 1)
			#M subwords["\\<" w "\\("] = "\\fB" w "\\fP("
			subwords["\\<" w "\\("] = "\\textbf{" w "}("
		}
	}
	# word attributes
	n = asorti(subwords, indices)
	for (i = 1; i <= n; i++)
		gsub(indices[i], subwords[indices[i]])
	# shell options
	#M gsub(/\b\-+\w+(\-\w+)*/, "\\fb&\\fp")
	gsub(/\b\-+\w+(\-\w+)*/, "\\textbf{&}")
	# unprotect dots inside words
	gsub(/_dOt_/, ".")

    if (section == "SYNOPSIS") {
		sub(/^  /, "")
		print
		next
	}
	if (match($0, /[^ ]  +/) > 0) {
		# tag list item
        #M
        if ((in_desc+0) == 0){
            in_desc = start_list(in_desc, "description")
        }
		adjust_indent()
		tag = substr($0, 1, RSTART)
		sub(/^ */, "", tag)
		if (RSTART+RLENGTH < length())
			$0 = substr($0, RSTART + RLENGTH)
		else
			$0 = ""
        #M print ".TP\n.B"
        print "\\item[" tag "]"
		#M print tag
		prevblankline = 0
		if (NF == 0)
			next
	} else if ($1 == "-"||$1 == "o"||$1 == "*") {
		# bullet list item
        #M
        if ((in_list+0) == 0){
            in_list = start_list(in_item, "itemize")
        }
		adjust_indent()
		#M print ".IP \\(bu 3"
        print "\\item"
		prevblankline = 0
		$1 = ""
	} else if ($1 ~ /^[0-9]+[\).]$/) {
		# enum list item
        if ((in_enum+0) == 0){
            in_enum = start_list(in_item, "enumerate")
        }
		adjust_indent()
		#M print ".IP " $1 " 4"
        print "\\item"
		prevblankline = 0
		$1 = ""
	} else if (pls == 0) {
		# new paragraph
		adjust_indent()
	} else if (NF == 0) {
		# blank line
        # print "BLANK"
		prevblankline = 1
        in_list=end_list(in_list,"itemize")
        in_desc=end_list(in_desc,"description")
        in_enum=end_list(in_enum,"enumerate")
        print $0
		next
	} else
		prevblankline = 0
	# flush vertical space
	if (prevblankline == 1) {
		#M print ".PP"
		prevblankline = 0
	}
	if (section != "SYNOPSIS" || $0 ~ /^ {1,4}/)
		sub(/ */,"")
	# Protect lines starting by simple quotes
	sub(/^'\''/, "\\(cq")
	print
}



function adjust_indent(){
	if (ls > ind[ni]) {
		ind[++ni] = ls
		#M print ".RS"
	} else if (ls < ind[ni]) {
		while (ls < ind[ni]) {
			ni--
			#M print ".RE"
		}
	}
}

function escape (s){
    gsub(/\\/, "\\textbackslash\\", s)
    gsub(/#/,"\\#", s)
    gsub(/\$/,"\\$", s)
    gsub(/%/,"\\%", s)
    gsub(/&/,"\\\\&", s)
    gsub(/{/, "\\{", s)
    gsub(/}/, "\\}", s)
    gsub(/_/, "\\\_", s)
    gsub(/\^/, "\\^\\", s)
    return s
}

function fmtmath (s){
    line = s
    math=""
    text=""
    sout=""
    i=0
    in_math = 0
    while (match(line, /\$([^$]*)\$/, m)) {
        in_math=1
        math = m[0]
        text = substr(line, i, i+RSTART-1)
        line = substr(line, RSTART + RLENGTH)
        text = escape(text)
        sout = sout text math
    }
    if (in_math == 1) {
        line = escape(line)
        sout = sout line
    }else{
        sout = escape(line)
    }

    return sout
}

function end_list(s, env){
    if ((s+0)==1){
        print "\\end{"env"}"
    }
    return 0
}

function start_list(s, env){
    if ((s+0)==0){
        print "\\begin{"env"}"
    }
    return 1
}

function start_article(title,author,date) { 
    print "\\documentclass[10pt,notitlepage]{article}" 
    split(ptxt, tt, "§")
        for (i in tt)
            if (tt[i] != "")
                print tt[i]
    print "\\title{"title"}"
    print "\\author{"author"}"
    print "\\date{"date"}"
}

function start_document() { print "\\begin{document}\n\\maketitle\n" }

function end_document() { print "\\end{document}" }
' | eval $post
